using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class JunctionController : MonoBehaviour
{
    public Vector2 position;
    public bool autogenerated; // Is true if the buffer was auto-generated

    public override string ToString() {
        return "J"+position;
    }

    public void connectLine(LineController line) {
        if(line.start == position){
            line.setStartJunction(this);
        }else if(line.end == position){
            line.setEndJunction(this);
        }else{
            throw new Exception("Inconsistency making connections for junction "+ this +"! The line "+ line +" doesn't start or end here.");
        }
    }

}
