using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class JunctionController : MonoBehaviour
{

    private LineController startline;
    private LineController mainline;
    private LineController branchline;

    private bool direction = true; // True - mainline, false - branchline
    private Vector2 position;
    public bool autogenerated; // Is true if the buffer was auto-generated

    public void Setup(Vector2 position, LineController startline, LineController mainline, LineController branchline, bool autogenerated=false) {
        gameObject.transform.position = position;

        this.position = position;
        this.startline = startline;
        this.mainline = mainline;
        this.branchline = branchline;

        this.autogenerated = autogenerated;

        // Connect lines to the junction
        connectLine(startline);
        connectLine(mainline);
        connectLine(branchline);
    }

    public void switchLine() {
        direction = !direction;
    }

    public LineController nextLine(LineController fromline) {
        if(fromline == startline){
            if(direction) { return mainline; }
            else          { return branchline; }
        }else if(fromline == mainline){
            if(direction) { return startline; }
            else          { return null; } // Train can't go this way
        }else if(fromline == branchline){
            if(direction) { return null; } // Train can't go this way
            else          { return mainline; }
        }else{ // fromline is not connected to this junction
            return null;
            //throw new Exception("Specified fromline "+ fromline +" is not a connection of this junction.");
        }
    }

    public override string ToString() {
        return "J"+position;
    }

    private void connectLine(LineController line) {
        if(line.start == position){
            line.setStartJunction(this);
        }else if(line.end == position){
            line.setEndJunction(this);
        }else{
            // throw new Exception("Inconsistency making connections for junction "+ this +"! The line "+ line +" doesn't start or end here.");
        }
    }

    // Update is called once per frame
    void Update()
    {

    }
}
