using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LineController : MonoBehaviour
{
    private LineRenderer lr;
    private Vector2[] nodes;

    public Vector2 start;
    public Vector2 end;

    public object startJunction;
    public object endJunction;

    private void Awake() {
      lr = GetComponent<LineRenderer>();
    }

    public void SetupLine(Vector2[] nodes) {
      lr.positionCount = nodes.Length;
      this.nodes = nodes;
      start = nodes[0];
      end = nodes[^1];

      // Set placeholder junctions (buffers)
      startJunction = Instantiate(bufferPrefab, start, Quaternion.identity).GetComponent<BufferController>();
      endJunction = Instantiate(bufferPrefab, end, Quaternion.identity).GetComponent<BufferController>();
      startJunction.Setup(start, this, autogenerated=true);
      endJunction.Setup(end, this, autogenerated=true);
    }

    public void setStartJunction(JunctionController junction) {
        if(startJunction.autogenerated == false){ // Trying to overwrite an already set junction
            throw new Exception("Attempted to override start junction of the line "+ this);
        }
        this.startJunction = junction;
    }

    public void setEndJunction(JunctionController junction) {
        if(endJunction.autogenerated == false){ // Trying to overwrite an already set junction
            throw new Exception("Attempted to override end junction of the line "+ this);
        }
        this.endJunction = junction;
    }

    // Start is called before the first frame update
    public void Start()
    {
    }

    // Update is called once per frame
    public void Update()
    {
        for (int i=0; i < nodes.Length; i++) {
            lr.SetPosition(i, nodes[i]);
        }
    }

    public override string ToString() {
        return "L"+start+"->"+end;
    }
}
